// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "HostInput.pb.h"

@implementation HostInputRoot
static id<PBExtensionField> HostInputRoot_hostbytes = nil;
static id<PBExtensionField> HostInputRoot_resize = nil;
static id<PBExtensionField> HostInputRoot_echoack = nil;
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [HostInputRoot class]) {
    HostInputRoot_hostbytes =
      [[PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[Instruction class]
                                       fieldNumber:2
                                      defaultValue:[HostBytes defaultInstance]
                               messageOrGroupClass:[HostBytes class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:NO] retain];
    HostInputRoot_resize =
      [[PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[Instruction class]
                                       fieldNumber:3
                                      defaultValue:[ResizeMessage defaultInstance]
                               messageOrGroupClass:[ResizeMessage class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:NO] retain];
    HostInputRoot_echoack =
      [[PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[Instruction class]
                                       fieldNumber:7
                                      defaultValue:[EchoAck defaultInstance]
                               messageOrGroupClass:[EchoAck class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:NO] retain];
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
  [registry addExtension:HostInputRoot_hostbytes];
  [registry addExtension:HostInputRoot_resize];
  [registry addExtension:HostInputRoot_echoack];
}
+ (id<PBExtensionField>) hostbytes {
  return HostInputRoot_hostbytes;
}
+ (id<PBExtensionField>) resize {
  return HostInputRoot_resize;
}
+ (id<PBExtensionField>) echoack {
  return HostInputRoot_echoack;
}
@end

@interface HostMessage ()
@property (retain) NSMutableArray* mutableInstructionList;
@end

@implementation HostMessage

@synthesize mutableInstructionList;
- (void) dealloc {
  self.mutableInstructionList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static HostMessage* defaultHostMessageInstance = nil;
+ (void) initialize {
  if (self == [HostMessage class]) {
    defaultHostMessageInstance = [[HostMessage alloc] init];
  }
}
+ (HostMessage*) defaultInstance {
  return defaultHostMessageInstance;
}
- (HostMessage*) defaultInstance {
  return defaultHostMessageInstance;
}
- (NSArray*) instructionList {
  return mutableInstructionList;
}
- (Instruction*) instructionAtIndex:(int32_t) index {
  id value = [mutableInstructionList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (Instruction* element in self.instructionList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (Instruction* element in self.instructionList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (Instruction* element in self.instructionList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (HostMessage*) parseFromData:(NSData*) data {
  return (HostMessage*)[[[HostMessage builder] mergeFromData:data] build];
}
+ (HostMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostMessage*)[[[HostMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (HostMessage*) parseFromInputStream:(NSInputStream*) input {
  return (HostMessage*)[[[HostMessage builder] mergeFromInputStream:input] build];
}
+ (HostMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostMessage*)[[[HostMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HostMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (HostMessage*)[[[HostMessage builder] mergeFromCodedInputStream:input] build];
}
+ (HostMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostMessage*)[[[HostMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HostMessage_Builder*) builder {
  return [[[HostMessage_Builder alloc] init] autorelease];
}
+ (HostMessage_Builder*) builderWithPrototype:(HostMessage*) prototype {
  return [[HostMessage builder] mergeFrom:prototype];
}
- (HostMessage_Builder*) builder {
  return [HostMessage builder];
}
@end

@interface HostMessage_Builder()
@property (retain) HostMessage* result;
@end

@implementation HostMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[HostMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (HostMessage_Builder*) clear {
  self.result = [[[HostMessage alloc] init] autorelease];
  return self;
}
- (HostMessage_Builder*) clone {
  return [HostMessage builderWithPrototype:result];
}
- (HostMessage*) defaultInstance {
  return [HostMessage defaultInstance];
}
- (HostMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (HostMessage*) buildPartial {
  HostMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (HostMessage_Builder*) mergeFrom:(HostMessage*) other {
  if (other == [HostMessage defaultInstance]) {
    return self;
  }
  if (other.mutableInstructionList.count > 0) {
    if (result.mutableInstructionList == nil) {
      result.mutableInstructionList = [NSMutableArray array];
    }
    [result.mutableInstructionList addObjectsFromArray:other.mutableInstructionList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (HostMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (HostMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Instruction_Builder* subBuilder = [Instruction builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addInstruction:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) instructionList {
  if (result.mutableInstructionList == nil) { return [NSArray array]; }
  return result.mutableInstructionList;
}
- (Instruction*) instructionAtIndex:(int32_t) index {
  return [result instructionAtIndex:index];
}
- (HostMessage_Builder*) replaceInstructionAtIndex:(int32_t) index with:(Instruction*) value {
  [result.mutableInstructionList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (HostMessage_Builder*) addAllInstruction:(NSArray*) values {
  if (result.mutableInstructionList == nil) {
    result.mutableInstructionList = [NSMutableArray array];
  }
  [result.mutableInstructionList addObjectsFromArray:values];
  return self;
}
- (HostMessage_Builder*) clearInstructionList {
  result.mutableInstructionList = nil;
  return self;
}
- (HostMessage_Builder*) addInstruction:(Instruction*) value {
  if (result.mutableInstructionList == nil) {
    result.mutableInstructionList = [NSMutableArray array];
  }
  [result.mutableInstructionList addObject:value];
  return self;
}
@end

@interface Instruction ()
@end

@implementation Instruction

- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static Instruction* defaultInstructionInstance = nil;
+ (void) initialize {
  if (self == [Instruction class]) {
    defaultInstructionInstance = [[Instruction alloc] init];
  }
}
+ (Instruction*) defaultInstance {
  return defaultInstructionInstance;
}
- (Instruction*) defaultInstance {
  return defaultInstructionInstance;
}
- (BOOL) isInitialized {
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self writeExtensionsToCodedOutputStream:output
                                      from:2
                                        to:536870912];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  size += [self extensionsSerializedSize];
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Instruction*) parseFromData:(NSData*) data {
  return (Instruction*)[[[Instruction builder] mergeFromData:data] build];
}
+ (Instruction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Instruction*)[[[Instruction builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Instruction*) parseFromInputStream:(NSInputStream*) input {
  return (Instruction*)[[[Instruction builder] mergeFromInputStream:input] build];
}
+ (Instruction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Instruction*)[[[Instruction builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Instruction*)[[[Instruction builder] mergeFromCodedInputStream:input] build];
}
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Instruction*)[[[Instruction builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Instruction_Builder*) builder {
  return [[[Instruction_Builder alloc] init] autorelease];
}
+ (Instruction_Builder*) builderWithPrototype:(Instruction*) prototype {
  return [[Instruction builder] mergeFrom:prototype];
}
- (Instruction_Builder*) builder {
  return [Instruction builder];
}
@end

@interface Instruction_Builder()
@property (retain) Instruction* result;
@end

@implementation Instruction_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Instruction alloc] init] autorelease];
  }
  return self;
}
- (PBExtendableMessage*) internalGetResult {
  return result;
}
- (Instruction_Builder*) clear {
  self.result = [[[Instruction alloc] init] autorelease];
  return self;
}
- (Instruction_Builder*) clone {
  return [Instruction builderWithPrototype:result];
}
- (Instruction*) defaultInstance {
  return [Instruction defaultInstance];
}
- (Instruction*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Instruction*) buildPartial {
  Instruction* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Instruction_Builder*) mergeFrom:(Instruction*) other {
  if (other == [Instruction defaultInstance]) {
    return self;
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface HostBytes ()
@property (retain) NSData* hoststring;
@end

@implementation HostBytes

- (BOOL) hasHoststring {
  return !!hasHoststring_;
}
- (void) setHasHoststring:(BOOL) value {
  hasHoststring_ = !!value;
}
@synthesize hoststring;
- (void) dealloc {
  self.hoststring = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.hoststring = [NSData data];
  }
  return self;
}
static HostBytes* defaultHostBytesInstance = nil;
+ (void) initialize {
  if (self == [HostBytes class]) {
    defaultHostBytesInstance = [[HostBytes alloc] init];
  }
}
+ (HostBytes*) defaultInstance {
  return defaultHostBytesInstance;
}
- (HostBytes*) defaultInstance {
  return defaultHostBytesInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasHoststring) {
    [output writeData:4 value:self.hoststring];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasHoststring) {
    size += computeDataSize(4, self.hoststring);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (HostBytes*) parseFromData:(NSData*) data {
  return (HostBytes*)[[[HostBytes builder] mergeFromData:data] build];
}
+ (HostBytes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostBytes*)[[[HostBytes builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (HostBytes*) parseFromInputStream:(NSInputStream*) input {
  return (HostBytes*)[[[HostBytes builder] mergeFromInputStream:input] build];
}
+ (HostBytes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostBytes*)[[[HostBytes builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HostBytes*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (HostBytes*)[[[HostBytes builder] mergeFromCodedInputStream:input] build];
}
+ (HostBytes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HostBytes*)[[[HostBytes builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HostBytes_Builder*) builder {
  return [[[HostBytes_Builder alloc] init] autorelease];
}
+ (HostBytes_Builder*) builderWithPrototype:(HostBytes*) prototype {
  return [[HostBytes builder] mergeFrom:prototype];
}
- (HostBytes_Builder*) builder {
  return [HostBytes builder];
}
@end

@interface HostBytes_Builder()
@property (retain) HostBytes* result;
@end

@implementation HostBytes_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[HostBytes alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (HostBytes_Builder*) clear {
  self.result = [[[HostBytes alloc] init] autorelease];
  return self;
}
- (HostBytes_Builder*) clone {
  return [HostBytes builderWithPrototype:result];
}
- (HostBytes*) defaultInstance {
  return [HostBytes defaultInstance];
}
- (HostBytes*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (HostBytes*) buildPartial {
  HostBytes* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (HostBytes_Builder*) mergeFrom:(HostBytes*) other {
  if (other == [HostBytes defaultInstance]) {
    return self;
  }
  if (other.hasHoststring) {
    [self setHoststring:other.hoststring];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (HostBytes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (HostBytes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 34: {
        [self setHoststring:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasHoststring {
  return result.hasHoststring;
}
- (NSData*) hoststring {
  return result.hoststring;
}
- (HostBytes_Builder*) setHoststring:(NSData*) value {
  result.hasHoststring = YES;
  result.hoststring = value;
  return self;
}
- (HostBytes_Builder*) clearHoststring {
  result.hasHoststring = NO;
  result.hoststring = [NSData data];
  return self;
}
@end

@interface ResizeMessage ()
@property int32_t width;
@property int32_t height;
@end

@implementation ResizeMessage

- (BOOL) hasWidth {
  return !!hasWidth_;
}
- (void) setHasWidth:(BOOL) value {
  hasWidth_ = !!value;
}
@synthesize width;
- (BOOL) hasHeight {
  return !!hasHeight_;
}
- (void) setHasHeight:(BOOL) value {
  hasHeight_ = !!value;
}
@synthesize height;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.width = 0;
    self.height = 0;
  }
  return self;
}
static ResizeMessage* defaultResizeMessageInstance = nil;
+ (void) initialize {
  if (self == [ResizeMessage class]) {
    defaultResizeMessageInstance = [[ResizeMessage alloc] init];
  }
}
+ (ResizeMessage*) defaultInstance {
  return defaultResizeMessageInstance;
}
- (ResizeMessage*) defaultInstance {
  return defaultResizeMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasWidth) {
    [output writeInt32:5 value:self.width];
  }
  if (self.hasHeight) {
    [output writeInt32:6 value:self.height];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasWidth) {
    size += computeInt32Size(5, self.width);
  }
  if (self.hasHeight) {
    size += computeInt32Size(6, self.height);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ResizeMessage*) parseFromData:(NSData*) data {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromData:data] build];
}
+ (ResizeMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ResizeMessage*) parseFromInputStream:(NSInputStream*) input {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromInputStream:input] build];
}
+ (ResizeMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResizeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromCodedInputStream:input] build];
}
+ (ResizeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResizeMessage*)[[[ResizeMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResizeMessage_Builder*) builder {
  return [[[ResizeMessage_Builder alloc] init] autorelease];
}
+ (ResizeMessage_Builder*) builderWithPrototype:(ResizeMessage*) prototype {
  return [[ResizeMessage builder] mergeFrom:prototype];
}
- (ResizeMessage_Builder*) builder {
  return [ResizeMessage builder];
}
@end

@interface ResizeMessage_Builder()
@property (retain) ResizeMessage* result;
@end

@implementation ResizeMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ResizeMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ResizeMessage_Builder*) clear {
  self.result = [[[ResizeMessage alloc] init] autorelease];
  return self;
}
- (ResizeMessage_Builder*) clone {
  return [ResizeMessage builderWithPrototype:result];
}
- (ResizeMessage*) defaultInstance {
  return [ResizeMessage defaultInstance];
}
- (ResizeMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ResizeMessage*) buildPartial {
  ResizeMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ResizeMessage_Builder*) mergeFrom:(ResizeMessage*) other {
  if (other == [ResizeMessage defaultInstance]) {
    return self;
  }
  if (other.hasWidth) {
    [self setWidth:other.width];
  }
  if (other.hasHeight) {
    [self setHeight:other.height];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ResizeMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ResizeMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 40: {
        [self setWidth:[input readInt32]];
        break;
      }
      case 48: {
        [self setHeight:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasWidth {
  return result.hasWidth;
}
- (int32_t) width {
  return result.width;
}
- (ResizeMessage_Builder*) setWidth:(int32_t) value {
  result.hasWidth = YES;
  result.width = value;
  return self;
}
- (ResizeMessage_Builder*) clearWidth {
  result.hasWidth = NO;
  result.width = 0;
  return self;
}
- (BOOL) hasHeight {
  return result.hasHeight;
}
- (int32_t) height {
  return result.height;
}
- (ResizeMessage_Builder*) setHeight:(int32_t) value {
  result.hasHeight = YES;
  result.height = value;
  return self;
}
- (ResizeMessage_Builder*) clearHeight {
  result.hasHeight = NO;
  result.height = 0;
  return self;
}
@end

@interface EchoAck ()
@property int64_t echoAckNum;
@end

@implementation EchoAck

- (BOOL) hasEchoAckNum {
  return !!hasEchoAckNum_;
}
- (void) setHasEchoAckNum:(BOOL) value {
  hasEchoAckNum_ = !!value;
}
@synthesize echoAckNum;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.echoAckNum = 0L;
  }
  return self;
}
static EchoAck* defaultEchoAckInstance = nil;
+ (void) initialize {
  if (self == [EchoAck class]) {
    defaultEchoAckInstance = [[EchoAck alloc] init];
  }
}
+ (EchoAck*) defaultInstance {
  return defaultEchoAckInstance;
}
- (EchoAck*) defaultInstance {
  return defaultEchoAckInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasEchoAckNum) {
    [output writeUInt64:8 value:self.echoAckNum];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasEchoAckNum) {
    size += computeUInt64Size(8, self.echoAckNum);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (EchoAck*) parseFromData:(NSData*) data {
  return (EchoAck*)[[[EchoAck builder] mergeFromData:data] build];
}
+ (EchoAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EchoAck*)[[[EchoAck builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (EchoAck*) parseFromInputStream:(NSInputStream*) input {
  return (EchoAck*)[[[EchoAck builder] mergeFromInputStream:input] build];
}
+ (EchoAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EchoAck*)[[[EchoAck builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (EchoAck*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (EchoAck*)[[[EchoAck builder] mergeFromCodedInputStream:input] build];
}
+ (EchoAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (EchoAck*)[[[EchoAck builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (EchoAck_Builder*) builder {
  return [[[EchoAck_Builder alloc] init] autorelease];
}
+ (EchoAck_Builder*) builderWithPrototype:(EchoAck*) prototype {
  return [[EchoAck builder] mergeFrom:prototype];
}
- (EchoAck_Builder*) builder {
  return [EchoAck builder];
}
@end

@interface EchoAck_Builder()
@property (retain) EchoAck* result;
@end

@implementation EchoAck_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[EchoAck alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (EchoAck_Builder*) clear {
  self.result = [[[EchoAck alloc] init] autorelease];
  return self;
}
- (EchoAck_Builder*) clone {
  return [EchoAck builderWithPrototype:result];
}
- (EchoAck*) defaultInstance {
  return [EchoAck defaultInstance];
}
- (EchoAck*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (EchoAck*) buildPartial {
  EchoAck* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (EchoAck_Builder*) mergeFrom:(EchoAck*) other {
  if (other == [EchoAck defaultInstance]) {
    return self;
  }
  if (other.hasEchoAckNum) {
    [self setEchoAckNum:other.echoAckNum];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (EchoAck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (EchoAck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 64: {
        [self setEchoAckNum:[input readUInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasEchoAckNum {
  return result.hasEchoAckNum;
}
- (int64_t) echoAckNum {
  return result.echoAckNum;
}
- (EchoAck_Builder*) setEchoAckNum:(int64_t) value {
  result.hasEchoAckNum = YES;
  result.echoAckNum = value;
  return self;
}
- (EchoAck_Builder*) clearEchoAckNum {
  result.hasEchoAckNum = NO;
  result.echoAckNum = 0L;
  return self;
}
@end

