// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class EchoAck;
@class EchoAck_Builder;
@class HostBytes;
@class HostBytes_Builder;
@class HostMessage;
@class HostMessage_Builder;
@class Instruction;
@class Instruction_Builder;
@class ResizeMessage;
@class ResizeMessage_Builder;

@interface HostInputRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) hostbytes;
+ (id<PBExtensionField>) resize;
+ (id<PBExtensionField>) echoack;
@end

@interface HostMessage : PBGeneratedMessage {
@private
  NSMutableArray* mutableInstructionList;
}
- (NSArray*) instructionList;
- (Instruction*) instructionAtIndex:(int32_t) index;

+ (HostMessage*) defaultInstance;
- (HostMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HostMessage_Builder*) builder;
+ (HostMessage_Builder*) builder;
+ (HostMessage_Builder*) builderWithPrototype:(HostMessage*) prototype;

+ (HostMessage*) parseFromData:(NSData*) data;
+ (HostMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostMessage*) parseFromInputStream:(NSInputStream*) input;
+ (HostMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HostMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HostMessage_Builder : PBGeneratedMessage_Builder {
@private
  HostMessage* result;
}

- (HostMessage*) defaultInstance;

- (HostMessage_Builder*) clear;
- (HostMessage_Builder*) clone;

- (HostMessage*) build;
- (HostMessage*) buildPartial;

- (HostMessage_Builder*) mergeFrom:(HostMessage*) other;
- (HostMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HostMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) instructionList;
- (Instruction*) instructionAtIndex:(int32_t) index;
- (HostMessage_Builder*) replaceInstructionAtIndex:(int32_t) index with:(Instruction*) value;
- (HostMessage_Builder*) addInstruction:(Instruction*) value;
- (HostMessage_Builder*) addAllInstruction:(NSArray*) values;
- (HostMessage_Builder*) clearInstructionList;
@end

@interface Instruction : PBExtendableMessage {
@private
}

+ (Instruction*) defaultInstance;
- (Instruction*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Instruction_Builder*) builder;
+ (Instruction_Builder*) builder;
+ (Instruction_Builder*) builderWithPrototype:(Instruction*) prototype;

+ (Instruction*) parseFromData:(NSData*) data;
+ (Instruction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Instruction*) parseFromInputStream:(NSInputStream*) input;
+ (Instruction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Instruction_Builder : PBExtendableMessage_Builder {
@private
  Instruction* result;
}

- (Instruction*) defaultInstance;

- (Instruction_Builder*) clear;
- (Instruction_Builder*) clone;

- (Instruction*) build;
- (Instruction*) buildPartial;

- (Instruction_Builder*) mergeFrom:(Instruction*) other;
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HostBytes : PBGeneratedMessage {
@private
  BOOL hasHoststring_:1;
  NSData* hoststring;
}
- (BOOL) hasHoststring;
@property (readonly, retain) NSData* hoststring;

+ (HostBytes*) defaultInstance;
- (HostBytes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HostBytes_Builder*) builder;
+ (HostBytes_Builder*) builder;
+ (HostBytes_Builder*) builderWithPrototype:(HostBytes*) prototype;

+ (HostBytes*) parseFromData:(NSData*) data;
+ (HostBytes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostBytes*) parseFromInputStream:(NSInputStream*) input;
+ (HostBytes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostBytes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HostBytes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HostBytes_Builder : PBGeneratedMessage_Builder {
@private
  HostBytes* result;
}

- (HostBytes*) defaultInstance;

- (HostBytes_Builder*) clear;
- (HostBytes_Builder*) clone;

- (HostBytes*) build;
- (HostBytes*) buildPartial;

- (HostBytes_Builder*) mergeFrom:(HostBytes*) other;
- (HostBytes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HostBytes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHoststring;
- (NSData*) hoststring;
- (HostBytes_Builder*) setHoststring:(NSData*) value;
- (HostBytes_Builder*) clearHoststring;
@end

@interface ResizeMessage : PBGeneratedMessage {
@private
  BOOL hasWidth_:1;
  BOOL hasHeight_:1;
  int32_t width;
  int32_t height;
}
- (BOOL) hasWidth;
- (BOOL) hasHeight;
@property (readonly) int32_t width;
@property (readonly) int32_t height;

+ (ResizeMessage*) defaultInstance;
- (ResizeMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResizeMessage_Builder*) builder;
+ (ResizeMessage_Builder*) builder;
+ (ResizeMessage_Builder*) builderWithPrototype:(ResizeMessage*) prototype;

+ (ResizeMessage*) parseFromData:(NSData*) data;
+ (ResizeMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResizeMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ResizeMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResizeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResizeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResizeMessage_Builder : PBGeneratedMessage_Builder {
@private
  ResizeMessage* result;
}

- (ResizeMessage*) defaultInstance;

- (ResizeMessage_Builder*) clear;
- (ResizeMessage_Builder*) clone;

- (ResizeMessage*) build;
- (ResizeMessage*) buildPartial;

- (ResizeMessage_Builder*) mergeFrom:(ResizeMessage*) other;
- (ResizeMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResizeMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasWidth;
- (int32_t) width;
- (ResizeMessage_Builder*) setWidth:(int32_t) value;
- (ResizeMessage_Builder*) clearWidth;

- (BOOL) hasHeight;
- (int32_t) height;
- (ResizeMessage_Builder*) setHeight:(int32_t) value;
- (ResizeMessage_Builder*) clearHeight;
@end

@interface EchoAck : PBGeneratedMessage {
@private
  BOOL hasEchoAckNum_:1;
  int64_t echoAckNum;
}
- (BOOL) hasEchoAckNum;
@property (readonly) int64_t echoAckNum;

+ (EchoAck*) defaultInstance;
- (EchoAck*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EchoAck_Builder*) builder;
+ (EchoAck_Builder*) builder;
+ (EchoAck_Builder*) builderWithPrototype:(EchoAck*) prototype;

+ (EchoAck*) parseFromData:(NSData*) data;
+ (EchoAck*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EchoAck*) parseFromInputStream:(NSInputStream*) input;
+ (EchoAck*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EchoAck*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EchoAck*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EchoAck_Builder : PBGeneratedMessage_Builder {
@private
  EchoAck* result;
}

- (EchoAck*) defaultInstance;

- (EchoAck_Builder*) clear;
- (EchoAck_Builder*) clone;

- (EchoAck*) build;
- (EchoAck*) buildPartial;

- (EchoAck_Builder*) mergeFrom:(EchoAck*) other;
- (EchoAck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EchoAck_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEchoAckNum;
- (int64_t) echoAckNum;
- (EchoAck_Builder*) setEchoAckNum:(int64_t) value;
- (EchoAck_Builder*) clearEchoAckNum;
@end

