// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Instruction;
@class Instruction_Builder;

@interface TransportInstructionRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Instruction : PBGeneratedMessage {
@private
  BOOL hasOldNum_:1;
  BOOL hasNewNum_:1;
  BOOL hasAckNum_:1;
  BOOL hasThrowawayNum_:1;
  BOOL hasDiff_:1;
  BOOL hasChaff_:1;
  BOOL hasProtocolVersion_:1;
  int64_t oldNum;
  int64_t newNum;
  int64_t ackNum;
  int64_t throwawayNum;
  NSData* diff;
  NSData* chaff;
  int32_t protocolVersion;
}
- (BOOL) hasProtocolVersion;
- (BOOL) hasOldNum;
- (BOOL) hasNewNum;
- (BOOL) hasAckNum;
- (BOOL) hasThrowawayNum;
- (BOOL) hasDiff;
- (BOOL) hasChaff;
@property (readonly) int32_t protocolVersion;
@property (readonly) int64_t oldNum;
@property (readonly) int64_t newNum;
@property (readonly) int64_t ackNum;
@property (readonly) int64_t throwawayNum;
@property (readonly, retain) NSData* diff;
@property (readonly, retain) NSData* chaff;

+ (Instruction*) defaultInstance;
- (Instruction*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Instruction_Builder*) builder;
+ (Instruction_Builder*) builder;
+ (Instruction_Builder*) builderWithPrototype:(Instruction*) prototype;

+ (Instruction*) parseFromData:(NSData*) data;
+ (Instruction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Instruction*) parseFromInputStream:(NSInputStream*) input;
+ (Instruction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Instruction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Instruction_Builder : PBGeneratedMessage_Builder {
@private
  Instruction* result;
}

- (Instruction*) defaultInstance;

- (Instruction_Builder*) clear;
- (Instruction_Builder*) clone;

- (Instruction*) build;
- (Instruction*) buildPartial;

- (Instruction_Builder*) mergeFrom:(Instruction*) other;
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Instruction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProtocolVersion;
- (int32_t) protocolVersion;
- (Instruction_Builder*) setProtocolVersion:(int32_t) value;
- (Instruction_Builder*) clearProtocolVersion;

- (BOOL) hasOldNum;
- (int64_t) oldNum;
- (Instruction_Builder*) setOldNum:(int64_t) value;
- (Instruction_Builder*) clearOldNum;

- (BOOL) hasNewNum;
- (int64_t) newNum;
- (Instruction_Builder*) setNewNum:(int64_t) value;
- (Instruction_Builder*) clearNewNum;

- (BOOL) hasAckNum;
- (int64_t) ackNum;
- (Instruction_Builder*) setAckNum:(int64_t) value;
- (Instruction_Builder*) clearAckNum;

- (BOOL) hasThrowawayNum;
- (int64_t) throwawayNum;
- (Instruction_Builder*) setThrowawayNum:(int64_t) value;
- (Instruction_Builder*) clearThrowawayNum;

- (BOOL) hasDiff;
- (NSData*) diff;
- (Instruction_Builder*) setDiff:(NSData*) value;
- (Instruction_Builder*) clearDiff;

- (BOOL) hasChaff;
- (NSData*) chaff;
- (Instruction_Builder*) setChaff:(NSData*) value;
- (Instruction_Builder*) clearChaff;
@end

